<?php

/**
 * Implements hook_theme().
 */
function site_location_time_theme($existing, $type, $theme, $path)
{
  return array(
    'site_location_time' => array(
      'variables' => [
        'title' => NULL,
        'description' => NULL,
        'current_date_time' => NULL,
        'country' => NULL,
        'city' => NULL,
      ],
      'template' => 'site-location-time'
    ),
  );
}
